# Generated by Django 3.0 on 2019-12-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='media/default.jpg', upload_to='media/profile_pictures'),
        ),
    ]
