# Generated by Django 3.0 on 2019-12-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20191223_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='media/default', upload_to='media/profile_pictures'),
        ),
    ]
