# Generated by Django 3.0 on 2020-01-01 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20191227_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wheelimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='post_images', verbose_name='Image'),
        ),
    ]
