# Generated by Django 3.0 on 2019-12-28 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0005_auto_20191227_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoltPattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bolt_pattern', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RingSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ring_size', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Width',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Wheel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('bolt_pattern', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.BoltPattern')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wheel', to='store.Post')),
                ('ring_size', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.RingSize')),
                ('width', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.Width')),
            ],
        ),
    ]
