# Generated by Django 3.0 on 2019-12-26 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0003_wheelimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bolt_Pattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boltpattern', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('idbrand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Brand')),
            ],
        ),
        migrations.CreateModel(
            name='RingSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ringsize', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Width',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.FloatField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Wheel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('offset', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=10)),
                ('bolt_pattern', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.Bolt_Pattern')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Color')),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.Material')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.Model')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.Post')),
                ('ring_size', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.RingSize')),
                ('width', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.Width')),
            ],
        ),
    ]
