# Generated by Django 3.0 on 2019-12-27 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20191227_0907'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wheel',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wheel', to='store.Post'),
        ),
    ]
