# Generated by Django 3.0 on 2020-01-07 07:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200107_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wheel',
            name='description',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(2500)]),
        ),
    ]
