# Generated by Django 3.0 on 2020-01-07 07:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200107_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wheel',
            name='offset',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(-50)]),
        ),
    ]
