# Generated by Django 3.0 on 2020-01-07 08:00

import django.core.validators
from django.db import migrations, models
import products.validators


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200107_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wheel',
            name='offset',
            field=models.IntegerField(blank=True, default=None, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(-50), products.validators.my_blank_validator]),
        ),
    ]
