# Generated by Django 3.0 on 2020-01-07 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200107_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wheel',
            name='offset',
            field=models.IntegerField(default=None),
        ),
    ]
