# Generated by Django 3.0 on 2020-01-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20200107_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wheel',
            name='condition',
            field=models.CharField(choices=[('NEW', 'New'), ('USED', 'Used')], max_length=4),
        ),
    ]
